version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=niwwrwog
      - POSTGRES_PASSWORD=koVVSE9GfjbwZdpB8g2jbu8UldFYExpF
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
